version: "3"

volumes:
    database:

services:
    database:
      image: mysql
      container_name: mysql
      volumes:
          - database:/var/lib/mysql
      ports:
          - ${DB_PORT}:3306
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
      restart: unless-stopped

    myAdmin:
      image: phpmyadmin
      container_name: myAdmin
      environment:
        PMA_HOST: database
        PMA_USER: root
        PMA_PASSWORD: ${DB_PASSWORD}
      ports:
          - 8080:80
      depends_on:
        - database
      restart: unless-stopped

